#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use BBLDN\LaravelModelToSymfonyEntityConverter\Command\ConvertCommand\Command as ConvertCommand;

$application = new Application();
$application->add(new ConvertCommand());

/** @noinspection PhpUnhandledExceptionInspection */
$application->run();